# Generated by Django 5.1.6 on 2026-09-12 17:30

import core.models
import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dm', 'Telegram DM'), ('group', 'Telegram group'), ('web', 'Web chat')], max_length=8)),
                ('external_id', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('locale', models.CharField(default='fr', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('connect_nudged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_active_at'], name='core_conver_last_ac_b254fe_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'external_id'), name='uniq_conversation_kind_external')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('web', 'Web')], max_length=10)),
                ('external_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('locale', models.CharField(default='fr', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_id'), name='uniq_participant_channel_external')],
            },
        ),
        migrations.CreateModel(
            name='FestroLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(max_length=255)),
                ('festro_display_name', models.CharField(blank=True, default='', max_length=120)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='festro_link', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('code_verifier', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conversation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_states', to='core.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PickSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(default=core.models._share_id, max_length=32, unique=True)),
                ('time_slot', models.CharField(blank=True, default='', max_length=40)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('picks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_sets', to='core.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_my_taste', models.BooleanField(default=False)),
                ('taste_consent_changed_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.conversation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('conversation', 'participant'), name='uniq_membership')],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='core.conversation')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='core.participant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='core_turn_convers_a78269_idx')],
            },
        ),
    ]
